//! The fast hashed-linear detector. Only compiled with the
//! `fast-language-detection` feature.
//!
//! User-facing prose lives on [`HashedLinearDetector`], not in this
//! private module's `//!` block. What stays here is the attribution note
//! and the internals' own reasoning.
//!
//! # Attribution
//!
//! The Latin model's feature definition (ASCII bigram/trigram/quadgram
//! packing, the non-ASCII codepoint-class table, MurmurHash2 bucketing)
//! follows `whichlang` v0.1.1 (MIT), whose design this workspace
//! differentially verified bit-exact against a reimplementation on
//! 20,052 cases before adopting it. The Cyrillic model's feature set is
//! Verbora's own — see [`hashed_features_cyrillic`] for the measured
//! reason `whichlang`'s cannot separate Russian from Ukrainian. The
//! weight *values* everywhere are Verbora's own, trained by
//! `tools/langdetect-train` on this detector's 18 statistically-modeled
//! languages (`whichlang` covers 13 of this crate's 22).

use crate::{Confidence, Language, LanguageDetection, LanguageDetector, Script, detect_script};

/// Generated by `tools/langdetect-train` (see its README for the corpus,
/// seed, and reproduction steps) — never edited by hand. The tables are
/// `static [f32; N]` arrays rather than runtime-loaded slices because the
/// scoring loop over a `&'static [f32; N]` compiles measurably tighter
/// (~2x on this workload) than the same loop over a fat-pointer slice.
#[allow(clippy::approx_constant, clippy::excessive_precision)]
mod weights {
    include!("hashed_linear_weights.rs");
}

/// Number of hash buckets. 4096 keeps the Latin table at 256 KB (16
/// classes × 4096 × 4 bytes) — small enough to stay cache-friendly, and
/// the dimension `whichlang` demonstrated is sufficient for 16-class
/// discrimination. Must match the trainer's dimension exactly; the
/// differential test in `tools/langdetect-train` pins that.
const DIMENSION: usize = 1 << 12;

/// MurmurHash2 seed, shared with the trainer. Same constant `whichlang`
/// uses; there is nothing special about the value beyond both sides
/// agreeing on it.
const SEED: u32 = 3_242_157_231;

const BIGRAM_MASK: u32 = (1 << 16) - 1;
const TRIGRAM_MASK: u32 = (1 << 24) - 1;

/// The 16 Latin-script languages, in [`Language::ALL`] order. Index k of
/// this array is class k of the Latin weight table — the trainer imports
/// this exact array, so model column order can never drift from the
/// enum's.
pub const LATIN_CLASSES: [Language; 16] = [
    Language::English,
    Language::Spanish,
    Language::Portuguese,
    Language::Italian,
    Language::French,
    Language::German,
    Language::Dutch,
    Language::Polish,
    Language::Indonesian,
    Language::Vietnamese,
    Language::Norwegian,
    Language::Swedish,
    Language::Finnish,
    Language::Galician,
    Language::Catalan,
    Language::Basque,
];

/// The 2 Cyrillic-script languages, in [`Language::ALL`] order. Same
/// contract as [`LATIN_CLASSES`].
pub const CYRILLIC_CLASSES: [Language; 2] = [Language::Russian, Language::Ukrainian];

/// Confidence reported when kana is present: hiragana and katakana are
/// used by no language other than Japanese, so this is nearly certain —
/// but not 1.0, because a kana *majority vote* can still be won by a
/// stray kana loanword inside otherwise non-Japanese text.
const KANA_CONFIDENCE: f32 = 0.95;

/// Confidence for Han-script text containing no kana at all. Reported as
/// Chinese, but kanji-only Japanese (headlines, signage) is a real false
/// positive this route cannot rule out — hence a deliberately modest
/// value a cautious [`LanguageDetection::best_above`] threshold can
/// reject.
const HAN_WITHOUT_KANA_CONFIDENCE: f32 = 0.7;

/// Confidence for Devanagari-script text, reported as Hindi. Devanagari
/// is also Marathi's, Nepali's, and Sanskrit's script and this detector
/// has no Devanagari-script model to tell them apart, so this is the
/// lowest of the script-routed confidences: right for the most common
/// case, honest about being a script-level (not language-level) call.
const DEVANAGARI_CONFIDENCE: f32 = 0.6;

/// One 32-bit MurmurHash2 round — `whichlang`'s hash, kept bit-identical
/// so the trainer and this module agree on bucket assignment by
/// construction.
#[inline(always)]
const fn murmurhash2(mut k: u32, seed: u32) -> u32 {
    const M: u32 = 0x5bd1_e995;
    let mut h: u32 = seed;
    k = k.wrapping_mul(M);
    k ^= k >> 24;
    k = k.wrapping_mul(M);
    h = h.wrapping_mul(M);
    h ^= k;
    h ^= h >> 13;
    h = h.wrapping_mul(M);
    h ^ (h >> 15)
}

/// Sorted codepoint boundaries for the non-ASCII coarse-class feature:
/// mostly Latin-1 letters that discriminate European languages, plus the
/// Japanese punctuation/kana/CJK ranges. A codepoint's class is its
/// `binary_search` insertion position — identical (values and order) to
/// `whichlang`'s table, per the attribution note in the module docs.
const CODEPOINT_CLASS_BOUNDS: [u32; 52] = [
    160, 161, 171, 172, 173, 174, 187, 192, 196, 199, 200, 201, 202, 205, 214, 220, 223, 224, 225,
    226, 227, 228, 231, 232, 233, 234, 235, 236, 237, 238, 239, 242, 243, 244, 245, 246, 249, 250,
    251, 252, 333, 339, 0x3000, 0x303F, 0x3040, 0x309F, 0x30A0, 0x30FF, 0x4E00, 0x9FAF, 0xFF61,
    0xFF90,
];

#[inline(always)]
fn classify_codepoint(chr: char) -> u32 {
    CODEPOINT_CLASS_BOUNDS
        .binary_search(&(chr as u32))
        .unwrap_or_else(|pos| pos) as u32
}

/// Streams `text`'s hashed feature buckets (each in `0..DIMENSION`) into
/// `emit`, allocating nothing. This is the Latin-model feature set.
///
/// ASCII runs contribute packed lowercase bigrams, trigrams, and
/// quadgrams (a run must be that long before the longer n-grams start);
/// non-alphanumeric ASCII resets the packing register to a space so
/// n-grams see word boundaries. Each non-ASCII character contributes two
/// features: its 128-codepoint block, and a coarse class read off a sorted
/// table of codepoint boundaries (mostly the Latin-1 letters that
/// discriminate European languages, plus the Japanese punctuation, kana and
/// CJK ranges) as that codepoint's `binary_search` insertion position. The
/// feature definitions are shared by training and inference —
/// the trainer calls *these functions* through [`crate::train_support`],
/// so the two can never diverge.
pub fn hashed_features(text: &str, mut emit: impl FnMut(u32)) {
    let mut packed = ' ' as u32;
    let mut ascii_run: u32 = 1;
    for chr in text.chars() {
        if !chr.is_ascii() {
            emit(murmurhash2(chr as u32 / 128, SEED ^ 2) % DIMENSION as u32);
            emit(murmurhash2(classify_codepoint(chr), SEED ^ 4) % DIMENSION as u32);
            ascii_run = 0;
            continue;
        }
        packed = packed << 8 | chr.to_ascii_lowercase() as u32;
        match ascii_run {
            0 => ascii_run = 1,
            1 => {
                emit(murmurhash2(packed & BIGRAM_MASK, SEED) % DIMENSION as u32);
                ascii_run = 2;
            }
            2 => {
                emit(murmurhash2(packed & BIGRAM_MASK, SEED) % DIMENSION as u32);
                emit(murmurhash2(packed & TRIGRAM_MASK, SEED) % DIMENSION as u32);
                ascii_run = 3;
            }
            _ => {
                emit(murmurhash2(packed & BIGRAM_MASK, SEED) % DIMENSION as u32);
                emit(murmurhash2(packed & TRIGRAM_MASK, SEED) % DIMENSION as u32);
                emit(murmurhash2(packed, SEED) % DIMENSION as u32);
            }
        }
        if !chr.is_alphanumeric() {
            packed = ' ' as u32;
        }
    }
}

/// Case-folds one codepoint for [`hashed_features_cyrillic`]: ASCII via
/// `to_ascii_lowercase`, every cased letter of `U+0400..=U+052F` via the
/// Unicode Cyrillic block layout, anything else unchanged. A tiny closed
/// mapping instead of `char::to_lowercase` so the hot loop stays a
/// handful of compares, and so the mapping is trivially auditable against
/// that layout.
///
/// The range is exactly the one [`Script::of`](crate::Script::of) routes
/// to the Cyrillic model, and the block is not laid out uniformly, so one
/// offset cannot serve all of it:
///
/// * `U+0410..=U+042F` (А–Я) and `U+0400..=U+040F` (Ѐ–Џ, including
///   Ё/Є/І/Ї) are contiguous uppercase runs at a fixed distance from
///   their lowercase runs.
/// * The historic and supplement letters are laid out as adjacent
///   uppercase/lowercase *pairs*: even-then-odd in `U+0460..=U+0481`,
///   `U+048A..=U+04BF` and `U+04D0..=U+052F`, but odd-then-even in
///   `U+04C1..=U+04CE` — the parity flips because `U+04C0` Ӏ PALOCHKA
///   takes the even slot ahead of them and pairs with `U+04CF` ӏ instead.
///
/// `fold_maps_every_cyrillic_letter_to_its_unicode_lowercase` pins this
/// against `char::to_lowercase` over the whole range, so a missed
/// sub-block is a test failure rather than silently lost signal — which
/// is what an earlier version of this function had: 100 uppercase letters
/// went unfolded, including `U+0490` Ґ, one of the four
/// Ukrainian-versus-Russian discriminators this model leans on.
#[inline(always)]
fn fold_cyrillic(chr: char) -> u32 {
    let cp = chr as u32;
    match cp {
        0x0410..=0x042F => cp + 0x20, // А..=Я -> а..=я
        0x0400..=0x040F => cp + 0x50, // Ѐ..=Џ -> ѐ..=џ (incl. Ё Є І Ї)
        // Adjacent pairs, uppercase on the even codepoint: Ѡ/ѡ..Ҁ/ҁ,
        // Ҋ/ҋ..Ҿ/ҿ, Ӑ/ӑ..Ԯ/ԯ (this last run holds Ґ/ґ at U+0490/U+0491).
        0x0460..=0x0481 | 0x048A..=0x04BF | 0x04D0..=0x052F => cp | 1,
        0x04C0 => 0x04CF, // Ӏ -> ӏ, the block's one non-adjacent pair
        // Adjacent pairs, uppercase on the *odd* codepoint: Ӂ/ӂ..Ӎ/ӎ.
        0x04C1..=0x04CE => cp + (cp & 1),
        _ => chr.to_ascii_lowercase() as u32,
    }
}

/// The Cyrillic-model feature set: hashed case-folded codepoint unigrams
/// plus in-word codepoint bigrams (each in `0..DIMENSION`), allocating
/// nothing.
///
/// A separate feature set exists because [`hashed_features`]'s
/// non-ASCII featurization is deliberately coarse — two features per
/// character, keyed by 128-codepoint *block* — which is enough to tell
/// scripts apart but structurally cannot separate two languages sharing
/// one block. Measured on this pipeline's own held-out split, Russian vs
/// Ukrainian under the coarse features scored 52%/64% — near chance —
/// while codepoint-level unigrams + bigrams resolve the two (Ukrainian's
/// і/ї/є/ґ vs Russian's ы/э/ъ/ё, plus their bigram contexts). `whichlang`
/// never hit this wall because its 16 languages include only one
/// Cyrillic-script language.
pub fn hashed_features_cyrillic(text: &str, mut emit: impl FnMut(u32)) {
    // 0 is never a folded alphabetic codepoint, so it can mark "word
    // boundary" without a separate flag.
    let mut prev: u32 = 0;
    for chr in text.chars() {
        if !chr.is_alphabetic() {
            prev = 0;
            continue;
        }
        let folded = fold_cyrillic(chr);
        emit(murmurhash2(folded, SEED ^ 8) % DIMENSION as u32);
        if prev != 0 {
            emit(murmurhash2(prev.wrapping_mul(65_599) ^ folded, SEED ^ 16) % DIMENSION as u32);
        }
        prev = folded;
    }
}

/// Which feature extractor a linear model was trained with — part of each
/// model's identity, so dispatch picks it alongside the weight table.
#[derive(Clone, Copy)]
enum FeatureSet {
    /// [`hashed_features`] — the Latin model.
    NGram,
    /// [`hashed_features_cyrillic`] — the Cyrillic model.
    CyrillicCodepoints,
}

/// Scores `text` against one interleaved weight table (`weights[bucket * N
/// + class]`) and returns `(argmax class, margin over the runner-up)`, or
/// `None` when the text produced no features at all.
///
/// The accumulation order is fixed (features in stream order, classes in
/// index order), the per-feature scaling is `1/sqrt(feature_count)` (so a
/// long text is a mean, not a sum, of its n-gram evidence — matching the
/// trainer's transform exactly), and ties break toward the lower class
/// index — all deterministic, per the module docs' determinism contract.
#[inline(always)]
fn linear_best_two<const N: usize, const T: usize>(
    text: &str,
    feature_set: FeatureSet,
    weights: &'static [f32; T],
    intercepts: &'static [f32; N],
) -> Option<(usize, f32)> {
    // `bucket * N + N <= T` for every bucket `hashed_features` can emit
    // (they are all `% DIMENSION`), so the row slice below cannot be out of
    // bounds. Checking the relation here makes that a compile error for a
    // mis-instantiated call rather than a runtime panic.
    const {
        assert!(T == DIMENSION * N, "weight table must be DIMENSION x N");
    }
    let mut scores = [0.0f32; N];
    let mut num_features: u32 = 0;
    let mut accumulate = |bucket: u32| {
        num_features += 1;
        let idx = bucket as usize * N;
        let row = &weights[idx..idx + N];
        for (score, &w) in scores.iter_mut().zip(row) {
            *score += w;
        }
    };
    match feature_set {
        FeatureSet::NGram => hashed_features(text, &mut accumulate),
        FeatureSet::CyrillicCodepoints => hashed_features_cyrillic(text, &mut accumulate),
    }
    if num_features == 0 {
        return None;
    }
    let inv = 1.0f32 / (num_features as f32).sqrt();
    for (score, &intercept) in scores.iter_mut().zip(intercepts) {
        *score = *score * inv + intercept;
    }
    let mut best = 0usize;
    let mut second = 1usize;
    for i in 1..N {
        if scores[i] > scores[best] {
            second = best;
            best = i;
        } else if scores[i] > scores[second] || second == best {
            second = i;
        }
    }
    Some((best, (scores[best] - scores[second]).max(0.0)))
}

/// Wraps one linear-model verdict as a [`LanguageDetection`]: margin below
/// the model's calibrated abstention threshold (or no features) is an
/// empty detection, anything else is a single candidate whose confidence
/// is the monotone squash `margin / (margin + 1)`.
fn linear_detection<const N: usize, const T: usize>(
    text: &str,
    feature_set: FeatureSet,
    weights: &'static [f32; T],
    intercepts: &'static [f32; N],
    abstain_margin: f32,
    classes: &[Language; N],
) -> LanguageDetection {
    let Some((best, margin)) = linear_best_two::<N, T>(text, feature_set, weights, intercepts)
    else {
        return LanguageDetection::none();
    };
    if margin < abstain_margin {
        return LanguageDetection::none();
    }
    single(classes[best], margin / (margin + 1.0))
}

/// A one-candidate detection — the only allocation any code path in this
/// module performs (the `candidates` `Vec` the public
/// [`LanguageDetection`] shape requires).
fn single(language: Language, confidence: f32) -> LanguageDetection {
    match Confidence::new(confidence) {
        Some(confidence) => LanguageDetection::single(language, confidence),
        // Unreachable for every constant and every squashed margin in this
        // module — `margin / (margin + 1)` is in `0.0..1.0` for every
        // non-negative, non-NaN margin, and `linear_best_two` clamps the
        // margin at 0 — but abstaining is the only honest answer if it ever
        // is not, and it keeps this module free of `unwrap`.
        None => LanguageDetection::none(),
    }
}

/// A latency-first [`LanguageDetector`] backed by compiled-in
/// hashed-linear models, staged behind [`detect_script`].
///
/// Stateless and zero-sized, like [`WhatlangDetector`](crate::WhatlangDetector):
/// the models are compile-time constants, so there is nothing to
/// construct, load, or share.
///
/// # Why this exists next to [`WhatlangDetector`](crate::WhatlangDetector)
///
/// This workspace measured where `whatlang`'s per-call time goes: its
/// trigram scorer probes a per-call `HashMap` once per profile trigram —
/// ~26 Latin profiles × 300 trigrams ≈ 7,800 probes *per call, independent
/// of input length* — plus ~26 heap allocations per call. A hashed-linear
/// model (the approach `whichlang` validated: hash each n-gram into a
/// fixed 4096-bucket table, accumulate per-language weights, argmax) has no
/// per-profile scan at all: cost scales with input length only, and the
/// inference loop performs zero heap allocations. See
/// `benches/language.rs`'s `fast_language_detection` group for the
/// latency this build measures.
///
/// This detector is **opt-in and additive**:
/// [`WhatlangDetector`](crate::WhatlangDetector) is untouched and remains
/// the accuracy reference. Nothing here changes any existing detection
/// output.
///
/// # What it deliberately does not claim
///
/// The linear models are trained on full sentences (Tatoeba corpus — see
/// `tools/langdetect-train/README.md` for the exact corpus, split, and
/// license attribution). **No short-input (single-word) accuracy claim is
/// made anywhere for this detector.** Single words are genuinely
/// ambiguous, and a caller who needs the best available judgement on hard
/// input should use [`WhatlangDetector`](crate::WhatlangDetector) — or
/// [`FallbackDetector`](crate::FallbackDetector), which pairs the two.
/// What this type offers instead of a blind guess is *abstention*: a margin
/// threshold calibrated on held-out data, below which it returns
/// [`LanguageDetection::none`] rather than a coin-flip candidate.
///
/// # Staged dispatch: script first, then the smallest possible model
///
/// [`detect_script`] is more reliable than any statistical model at what it
/// does, and far cheaper, so it runs first and picks the smallest class set
/// that can still be right:
///
/// | Script | Route |
/// |---|---|
/// | Latin | 16-class linear model (en/es/pt/it/fr/de/nl/pl/id/vi/no/sv/fi/gl/ca/eu) |
/// | Cyrillic | 2-class linear model (ru/uk) |
/// | Hiragana/Katakana | Japanese, directly — kana is used by no other language |
/// | Han | Japanese if any kana is present, else Chinese |
/// | Devanagari | Hindi (see the confidence table below for the caveat) |
/// | Arabic | **abstains** — see below |
/// | Greek/Hebrew/Hangul/other | abstains — no [`Language`] variant to answer with |
///
/// **The Arabic abstention guard.** Arabic script is shared by Arabic,
/// Persian, Urdu and others, and Persian is the only one of those in
/// [`Language`]. Mapping every Arabic-script input to
/// [`Language::Persian`] would be wrong for most real Arabic-script text,
/// so this detector abstains instead of mislabelling it. That makes
/// Persian the one [`Language`] this detector can never return — a
/// documented limitation, not an accident. Use
/// [`WhatlangDetector`](crate::WhatlangDetector), whose trigram profiles do
/// distinguish Arabic-script languages, when Persian matters.
///
/// # What `confidence` means here
///
/// For the linear-model routes (Latin, Cyrillic): a squash of the score
/// margin between the winning language and the runner-up — monotone in the
/// model's own certainty, **not** a calibrated probability, and not
/// comparable to [`WhatlangDetector`](crate::WhatlangDetector)'s (see
/// [`Confidence`]). For the script-determined routes, a fixed constant per
/// route, each chosen to be honest about what the script alone can and
/// cannot establish:
///
/// | Route | Confidence | Why not higher |
/// |---|---|---|
/// | kana present → Japanese | `0.95` | Hiragana and katakana are used by no other language, so this is nearly certain — but the majority vote can still be won by a stray kana loanword inside otherwise non-Japanese text. |
/// | Han, no kana → Chinese | `0.7` | Kanji-only Japanese (headlines, signage) is a real false positive this route cannot rule out, so the value is deliberately modest enough for a cautious [`LanguageDetection::best_above`] threshold to reject. |
/// | Devanagari → Hindi | `0.6` | Devanagari is also Marathi's, Nepali's and Sanskrit's script and this detector has no Devanagari model to tell them apart: right for the most common case, but a script-level call, not a language-level one. |
///
/// # Determinism
///
/// Every path is deterministic and bit-reproducible: the weight tables are
/// compile-time constants, `f32` accumulation happens in one fixed order,
/// and every operation used (`+`, `*`, `sqrt`) is IEEE-754
/// correctly-rounded — so the same input produces bit-identical
/// confidences on every platform and every call. This crate's own tests
/// assert exact `f32` bit patterns, not approximate closeness.
#[derive(Debug, Clone, Copy, Default)]
pub struct HashedLinearDetector;

impl HashedLinearDetector {
    /// A new detector. Free — nothing to initialize.
    #[must_use]
    pub const fn new() -> Self {
        Self
    }
}

impl LanguageDetector for HashedLinearDetector {
    fn detect(&self, input: &str) -> LanguageDetection {
        let Some(script) = detect_script(input) else {
            // No classifiable letters at all (empty, digits, punctuation,
            // emoji): nothing any model could work with.
            return LanguageDetection::none();
        };
        match script {
            Script::Latin => linear_detection::<16, { DIMENSION * 16 }>(
                input,
                FeatureSet::NGram,
                &weights::LATIN_WEIGHTS,
                &weights::LATIN_INTERCEPTS,
                weights::LATIN_ABSTAIN_MARGIN,
                &LATIN_CLASSES,
            ),
            Script::Cyrillic => linear_detection::<2, { DIMENSION * 2 }>(
                input,
                FeatureSet::CyrillicCodepoints,
                &weights::CYRILLIC_WEIGHTS,
                &weights::CYRILLIC_INTERCEPTS,
                weights::CYRILLIC_ABSTAIN_MARGIN,
                &CYRILLIC_CLASSES,
            ),
            Script::Hiragana | Script::Katakana => single(Language::Japanese, KANA_CONFIDENCE),
            Script::Han => {
                // A Han majority with any kana at all is Japanese prose
                // (kanji + grammatical kana); kana-free Han text is
                // routed as Chinese, with the caveat documented on the
                // constant.
                if input
                    .chars()
                    .any(|c| matches!(Script::of(c), Some(Script::Hiragana | Script::Katakana)))
                {
                    single(Language::Japanese, KANA_CONFIDENCE)
                } else {
                    single(Language::Chinese, HAN_WITHOUT_KANA_CONFIDENCE)
                }
            }
            Script::Devanagari => single(Language::Hindi, DEVANAGARI_CONFIDENCE),
            // The Arabic abstention guard — see the module docs: Persian
            // is the only Arabic-script Language variant, and most real
            // Arabic-script text is not Persian, so an honest detector
            // abstains rather than mislabels.
            Script::Arabic => LanguageDetection::none(),
            // Greek, Hebrew, Hangul, Other, and any future Script
            // variant: no Language in this crate to answer with.
            _ => LanguageDetection::none(),
        }
    }
}

/// Train-time support surface for `tools/langdetect-train` — **not public
/// API**, exempt from semver, and of no use to detector callers.
///
/// The trainer must transform text into feature buckets *exactly* as
/// inference does; re-exporting the very functions inference runs (rather
/// than letting the trainer copy them) makes that equality true by
/// construction instead of by discipline. The trainer's own test suite
/// additionally pins the stream against an independently verified
/// reference implementation.
#[doc(hidden)]
pub mod train_support {
    pub use super::{CYRILLIC_CLASSES, LATIN_CLASSES, hashed_features, hashed_features_cyrillic};

    /// Bucket count of the hashed feature space (`hashed_features` emits
    /// values in `0..DIMENSION`).
    pub const DIMENSION: usize = super::DIMENSION;
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The corpus this module is checked against, as `(input, expected)`.
    ///
    /// The two columns are **not** the same kind of claim, and the tests
    /// below keep them apart deliberately:
    ///
    /// * The **language** is ground truth about the sentence. "Das Wetter
    ///   ist heute schön" is German whatever this crate does, so
    ///   `every_corpus_sentence_detects_as_its_own_language` asserts a
    ///   fact, not a recording.
    /// * The **confidence bits** are a fingerprint of the committed weight
    ///   tables. No standard predicts them; they are the output of a
    ///   trained model, and `committed_weight_tables_have_not_changed`
    ///   exists to make a silent retrain impossible, not to specify a
    ///   value. Regenerating the weights legitimately changes them —
    ///   `tools/langdetect-train`'s `golden` subcommand reprints this
    ///   table; update it only alongside a deliberate, documented retrain.
    ///
    /// Rows with `None` are pinned abstentions, and those *are* contract:
    /// the Arabic guard and the unsupported scripts are documented
    /// behaviour, not model output.
    const GOLDEN: &[(&str, Option<(Language, u32)>)] = &[
        // Latin linear model, one clear sentence per well-resourced class.
        (
            "The weather is beautiful today and the children are playing outside.",
            Some((Language::English, 0x3F7369DE)),
        ),
        (
            "El tiempo es hermoso hoy y los niños juegan afuera en el parque.",
            Some((Language::Spanish, 0x3F6FC569)),
        ),
        (
            "O tempo está bonito hoje e as crianças brincam lá fora no parque.",
            Some((Language::Portuguese, 0x3F601781)),
        ),
        (
            "Il tempo è bello oggi e i bambini giocano fuori nel parco.",
            Some((Language::Italian, 0x3F6D903D)),
        ),
        (
            "Le temps est magnifique aujourd'hui et les enfants jouent dehors.",
            Some((Language::French, 0x3F6B033B)),
        ),
        (
            "Das Wetter ist heute schön und die Kinder spielen draußen im Park.",
            Some((Language::German, 0x3F6F9FAC)),
        ),
        (
            "Het weer is vandaag mooi en de kinderen spelen buiten in het park.",
            Some((Language::Dutch, 0x3F6E92C1)),
        ),
        (
            "Pogoda jest dziś piękna, a dzieci bawią się na dworze w parku.",
            Some((Language::Polish, 0x3F746E05)),
        ),
        (
            "Cuaca hari ini sangat cerah dan anak-anak bermain di luar taman.",
            Some((Language::Indonesian, 0x3F6F6B63)),
        ),
        (
            "Hôm nay trời đẹp và trẻ em đang chơi ở ngoài công viên.",
            Some((Language::Vietnamese, 0x3F7702B0)),
        ),
        (
            "Været er fint i dag og barna leker ute i parken sammen.",
            Some((Language::Norwegian, 0x3F577FBF)),
        ),
        (
            "Vädret är vackert idag och barnen leker ute i parken tillsammans.",
            Some((Language::Swedish, 0x3F696F88)),
        ),
        (
            "Sää on tänään kaunis ja lapset leikkivät ulkona puistossa.",
            Some((Language::Finnish, 0x3F6DCB52)),
        ),
        (
            "O tempo hoxe está fermoso e os nenos xogan fóra no parque.",
            Some((Language::Galician, 0x3F6C25F5)),
        ),
        (
            "El temps és preciós avui i els nens juguen a fora al parc.",
            Some((Language::Catalan, 0x3F6DF042)),
        ),
        (
            "Gaur eguraldi ederra dago eta haurrak kanpoan jolasten ari dira.",
            Some((Language::Basque, 0x3F720180)),
        ),
        // Cyrillic linear model.
        (
            "Сегодня прекрасная погода, и дети играют на улице в парке.",
            Some((Language::Russian, 0x3F51CCEE)),
        ),
        (
            "Сьогодні чудова погода, і діти граються надворі в парку.",
            Some((Language::Ukrainian, 0x3F73435F)),
        ),
        // Script-determined routes (fixed confidences, exact by
        // construction).
        (
            "これはにほんごのぶんしょうです",
            Some((Language::Japanese, 0x3F733333)),
        ),
        (
            "カタカナだけのブンショウ",
            Some((Language::Japanese, 0x3F733333)),
        ),
        // Han + kana → Japanese; kana-free Han → Chinese.
        (
            "日本語の文章はこう見えます",
            Some((Language::Japanese, 0x3F733333)),
        ),
        (
            "中文文章看起来是这样的",
            Some((Language::Chinese, 0x3F333333)),
        ),
        (
            "आज मौसम बहुत सुहावना है और बच्चे बाहर खेल रहे हैं",
            Some((Language::Hindi, 0x3F19999A)),
        ),
        // Pinned abstentions: the Arabic guard, unsupported scripts, and
        // no-signal input.
        ("اليوم الطقس جميل والأطفال يلعبون في الخارج", None),
        ("امروز هوا زیباست و بچه‌ها بیرون بازی می‌کنند", None),
        (
            "Σήμερα ο καιρός είναι όμορφος και τα παιδιά παίζουν έξω.",
            None,
        ),
        ("היום מזג האוויר יפה והילדים משחקים בחוץ", None),
        ("오늘은 날씨가 좋고 아이들이 밖에서 놀고 있어요", None),
        ("", None),
        ("12345 !!! ...", None),
        ("😀😀😀", None),
    ];

    #[test]
    fn every_corpus_sentence_detects_as_its_own_language() {
        // Ground truth: each sentence is written in the language named
        // beside it, and each abstention row is a documented dispatch rule
        // (the Arabic guard, an unsupported script, or no signal at all).
        // Nothing here is a recording of what the code emits.
        let d = HashedLinearDetector::new();
        for &(input, expected) in GOLDEN {
            let got = d.detect(input);
            match expected {
                None => assert_eq!(
                    got,
                    LanguageDetection::none(),
                    "expected abstention for {input:?}, got {got:?}"
                ),
                Some((language, _)) => {
                    let candidate = got
                        .best()
                        .unwrap_or_else(|| panic!("expected a candidate for {input:?}"));
                    assert_eq!(candidate.language, language, "wrong language for {input:?}");
                }
            }
        }
    }

    #[test]
    fn committed_weight_tables_have_not_changed() {
        // A change detector, not a specification. These bits are what the
        // committed weight tables produce; no publication predicts them.
        // A diff here means the model was retrained (fine, if deliberate
        // and documented) or the feature extraction drifted (not fine) —
        // and either way it must be read, not re-recorded.
        let d = HashedLinearDetector::new();
        for &(input, expected) in GOLDEN {
            let Some((_, confidence_bits)) = expected else {
                continue;
            };
            let got = d.detect(input);
            let candidate = got
                .best()
                .unwrap_or_else(|| panic!("expected a candidate for {input:?}"));
            assert_eq!(
                candidate.confidence.get().to_bits(),
                confidence_bits,
                "confidence drifted for {input:?}: {} (bits {:#010X})",
                candidate.confidence,
                candidate.confidence.get().to_bits()
            );
        }
    }

    #[test]
    fn detect_is_deterministic_and_bit_identical_across_repeated_calls() {
        // Stronger than WhatlangDetector's determinism test on purpose:
        // the module docs promise *bit* reproducibility, so compare
        // confidence bit patterns, not just PartialEq equality.
        let d = HashedLinearDetector::new();
        for &(input, _) in GOLDEN {
            let first = d.detect(input);
            for _ in 0..5 {
                let again = d.detect(input);
                assert_eq!(again, first, "detect({input:?}) not deterministic");
                assert_eq!(
                    again.best().map(|c| c.confidence.get().to_bits()),
                    first.best().map(|c| c.confidence.get().to_bits()),
                    "confidence bits drifted across calls for {input:?}"
                );
            }
        }
    }

    #[test]
    fn abstains_on_arabic_script_rather_than_guessing_persian() {
        // The one dispatch rule with a named guard in the module docs:
        // Arabic-script input must produce an empty detection — never a
        // Persian candidate — because most Arabic-script text is not
        // Persian and this detector has no Arabic-script model.
        let d = HashedLinearDetector::new();
        for input in [
            "العربية",
            "هذا نص عربي طويل بما يكفي ليكون واضحا تماما",
            "این یک جمله فارسی است", // even actual Persian abstains
        ] {
            assert_eq!(
                d.detect(input),
                LanguageDetection::none(),
                "Arabic-script input {input:?} must abstain"
            );
        }
    }

    #[test]
    fn abstains_on_scripts_with_no_language_variant() {
        let d = HashedLinearDetector::new();
        for input in ["ελληνικά", "עברית", "한국어 문장입니다"] {
            assert_eq!(d.detect(input), LanguageDetection::none());
        }
    }

    #[test]
    fn no_signal_input_returns_no_candidates() {
        let d = HashedLinearDetector::new();
        for input in ["", "   ", "12345", "!!! ??? ...", "😀😀😀"] {
            assert_eq!(d.detect(input), LanguageDetection::none());
        }
    }

    #[test]
    fn script_determined_routes_are_exact() {
        let d = HashedLinearDetector::new();
        let cases = [
            ("ひらがなだけ", Language::Japanese, KANA_CONFIDENCE),
            ("カタカナダケ", Language::Japanese, KANA_CONFIDENCE),
            ("日本語です", Language::Japanese, KANA_CONFIDENCE), // Han + kana
            ("中文文本", Language::Chinese, HAN_WITHOUT_KANA_CONFIDENCE),
            ("हिन्दी", Language::Hindi, DEVANAGARI_CONFIDENCE),
        ];
        for (input, language, confidence) in cases {
            let got = d.detect(input);
            let candidate = got.best().expect("script route must produce a candidate");
            assert_eq!(candidate.language, language, "for {input:?}");
            assert_eq!(
                candidate.confidence.get().to_bits(),
                confidence.to_bits(),
                "for {input:?}"
            );
        }
    }

    #[test]
    fn confidence_stays_in_bounds_and_never_panics_on_pathological_input() {
        let d = HashedLinearDetector::new();
        let long = "a".repeat(10_000);
        for input in [
            "Hello мир, this sentence mixes Latin and Cyrillic together.",
            "café naïve Москва東京",
            "one two 三四 пять",
            "\u{0}",
            "ß",
            long.as_str(),
        ] {
            let result = d.detect(input);
            if let Some(candidate) = result.best() {
                assert!(
                    (0.0..=1.0).contains(&candidate.confidence.get()),
                    "confidence out of [0, 1] for {input:?}: {}",
                    candidate.confidence
                );
            }
        }
    }

    #[test]
    fn low_margin_input_is_rejectable_via_best_above() {
        // The abstention/threshold contract from the module docs: a
        // single ambiguous word either abstains outright or comes back
        // with a confidence a modest best_above threshold rejects. No
        // accuracy claim — only that the caller keeps control.
        let d = HashedLinearDetector::new();
        for input in ["hotel", "radio", "piano", "normal", "color"] {
            let result = d.detect(input);
            if let Some(candidate) = result.best() {
                let high = Confidence::new(0.99).expect("0.99 is in range");
                assert!(
                    result.best_above(high).is_none() || candidate.confidence >= high,
                    "best_above must stay consistent with best for {input:?}"
                );
            }
        }
    }

    #[test]
    fn composes_with_auto_phonetic_strategy() {
        // HashedLinearDetector must drop into AutoPhoneticStrategy<D>
        // exactly like WhatlangDetector does — the trait is the contract,
        // not the concrete type.
        let auto = crate::AutoPhoneticStrategy::new(
            HashedLinearDetector::new(),
            Confidence::new(0.5).expect("0.5 is in range"),
        );
        let result =
            auto.detect_and_recommend("Das Wetter ist heute schön und die Kinder spielen draußen.");
        assert_eq!(
            result.detection.best().map(|c| c.language),
            Some(Language::German)
        );
    }

    #[test]
    fn fold_maps_every_cyrillic_letter_to_its_unicode_lowercase() {
        // The whole range `Script::of` routes to the Cyrillic model, not
        // just the two contiguous uppercase runs. `char::to_lowercase` is
        // the oracle; the hand-written fold exists only for speed, so any
        // codepoint where the two disagree is lost model capacity.
        let mut folded_something = 0u32;
        for cp in 0x0400..=0x052Fu32 {
            let chr = char::from_u32(cp).expect("BMP scalar");
            if !chr.is_alphabetic() {
                continue;
            }
            let mut lower = chr.to_lowercase();
            let first = lower.next().expect("to_lowercase yields at least one");
            assert!(
                lower.next().is_none(),
                "U+{cp:04X} lowercases to more than one scalar; the fold's \
                 one-codepoint-in/one-out shape cannot express that"
            );
            assert_eq!(
                fold_cyrillic(chr),
                first as u32,
                "fold_cyrillic(U+{cp:04X} {chr:?}) must equal its Unicode lowercase U+{:04X}",
                first as u32
            );
            if first != chr {
                folded_something += 1;
            }
        }
        // Guards the guard: a fold that returned its input unchanged
        // would satisfy every lowercase codepoint above and nothing else.
        // 148 uppercase letters live in this range; the two contiguous
        // runs this function originally handled cover 48 of them, so the
        // other 100 are exactly what the defect was losing.
        assert_eq!(
            folded_something, 148,
            "expected 148 cased letters in U+0400..=U+052F"
        );
    }

    #[test]
    fn cyrillic_detection_is_case_invariant() {
        // The Cyrillic model folds case before hashing, so the same text
        // in any case must produce a bit-identical detection. Uppercase
        // Cyrillic is ordinary in headlines and in all-caps names.
        let d = HashedLinearDetector::new();
        for input in [
            "родина мова слово",
            "ґудзик на ґанку ґрунтовно ґречно",
            "это русский текст про погоду",
            "щоденник української мови",
        ] {
            let upper: String = input.chars().flat_map(char::to_uppercase).collect();
            let lower = d.detect(input);
            let upcased = d.detect(&upper);
            assert_eq!(
                lower.best().map(|c| c.language),
                upcased.best().map(|c| c.language),
                "case changed the answer for {input:?} (upper {upper:?})"
            );
            assert_eq!(
                lower.best().map(|c| c.confidence.get().to_bits()),
                upcased.best().map(|c| c.confidence.get().to_bits()),
                "case changed the confidence for {input:?}"
            );
        }
    }

    #[test]
    fn detector_is_zero_sized_and_copy() {
        assert_eq!(std::mem::size_of::<HashedLinearDetector>(), 0);
        let d = HashedLinearDetector::new();
        let copy = d;
        let _ = d; // still usable: Copy
        let _ = copy;
    }
}
