//! Rule and lookup tables, transcribed verbatim from the reference.
//!
//! Machine-derived from the reference's own live objects (`inst.ambiguous`,
//! `inst.pluralForms.regularForms`, …) rather than retyped. The French `ambiguous` list alone is 744 accented, hyphenated and
//! occasionally space-containing entries; a hand transcription would be wrong,
//! and wrong in a way no reviewer would catch. `src/data_check.rs` re-checks
//! every table against the same tables recorded in `fixtures/inflectors.json`,
//! so a future edit cannot quietly drift from the reference either.
//!
//! Pattern `source` strings are the reference `RegExp.source` text, kept
//! verbatim and translated at load time by [`crate::pattern`]; they are *not*
//! Rust regex syntax. All of them carry `/i` and none carry `/g`.

/// A rule exactly as the reference declares it: a reference pattern plus what
/// to substitute for its first match.
pub(crate) struct RawRule {
    /// The reference `RegExp.source` text.
    pub(crate) source: &'static str,
    /// What replaces the match.
    pub(crate) replacement: RawReplacement,
}

/// The two shapes a reference replacement takes.
pub(crate) enum RawReplacement {
    /// A reference substitution template (`$1`, `$&`, …).
    Template(&'static str),
    /// The three Japanese rules whose replacement is a *function*: it re-appends
    /// `suffix` when the captured stem is in `exceptions` (leaving the word
    /// unchanged), and otherwise strips the suffix.
    KeepIfListed {
        /// Stems that must keep their suffix.
        exceptions: &'static [&'static str],
        /// The suffix the pattern matched, re-appended for exceptions.
        suffix: &'static str,
    },
}

/// English noun tables — the reference `noun_inflector`.
pub(crate) mod en {
    use super::{RawReplacement, RawRule};

    /// `this.ambiguous`: words that inflect to themselves. Sorted here so the
    /// membership test is a binary search rather tha reference's linear
    /// `Array.indexOf`; order is not observable because only membership is.
    pub(crate) static AMBIGUOUS: &[&str] = &[
        "bison",
        "bream",
        "carp",
        "chassis",
        "christmas",
        "cod",
        "corps",
        "debris",
        "deer",
        "diabetes",
        "elk",
        "equipment",
        "fish",
        "flounder",
        "gallows",
        "graffiti",
        "headquarters",
        "herpes",
        "highjinks",
        "homework",
        "information",
        "mackerel",
        "mews",
        "money",
        "news",
        "rabies",
        "rice",
        "salmon",
        "series",
        "sheep",
        "shrimp",
        "species",
        "swine",
        "tennis",
        "trout",
        "tuna",
        "whiting",
        "wildebeest",
    ];

    /// `pluralForms.irregularForms`: singular -> plural, after the
    /// last-write-wins collapse `addForm` performs. Sorted by key.
    pub(crate) static PLURAL_IRREGULAR: &[(&str, &str)] = &[
        ("calf", "calves"),
        ("child", "children"),
        ("cloth", "clothes"),
        ("ephemeris", "ephemerides"),
        ("foot", "feet"),
        ("goose", "geese"),
        ("half", "halves"),
        ("hero", "heroes"),
        ("knife", "knives"),
        ("leaf", "leaves"),
        ("life", "lives"),
        ("loaf", "loaves"),
        ("man", "men"),
        ("mouse", "mice"),
        ("ox", "oxen"),
        ("person", "people"),
        ("sex", "sexes"),
        ("shelf", "shelves"),
        ("thief", "thieves"),
        ("tooth", "teeth"),
        ("torso", "torsi"),
        ("wife", "wives"),
        ("wolf", "wolves"),
        ("yourself", "yourselves"),
    ];

    /// `singularForms.irregularForms`: plural -> singular, likewise collapsed.
    pub(crate) static SINGULAR_IRREGULAR: &[(&str, &str)] = &[
        ("calves", "calf"),
        ("children", "child"),
        ("clothes", "cloth"),
        ("ephemerides", "ephemeris"),
        ("feet", "foot"),
        ("geese", "goose"),
        ("halves", "half"),
        ("heroes", "hero"),
        ("knives", "knife"),
        ("leaves", "leaf"),
        ("lives", "life"),
        ("loaves", "loaf"),
        ("men", "man"),
        ("mice", "mouse"),
        ("oxen", "ox"),
        ("people", "person"),
        ("sexes", "sex"),
        ("shelves", "shelf"),
        ("teeth", "tooth"),
        ("thieves", "thief"),
        ("torsi", "torso"),
        ("wives", "wife"),
        ("wolves", "wolf"),
        ("yourselves", "yourself"),
    ];

    /// `pluralForms.regularForms` in source order. First match wins.
    pub(crate) static PLURAL_REGULAR: &[RawRule] = &[
        RawRule {
            source: "([aeiou]y)$",
            replacement: RawReplacement::Template("$1s"),
        },
        RawRule {
            source: "y$",
            replacement: RawReplacement::Template("ies"),
        },
        RawRule {
            source: "ife$",
            replacement: RawReplacement::Template("ives"),
        },
        RawRule {
            source: "(antenn|formul|nebul|vertebr|vit)a$",
            replacement: RawReplacement::Template("$1ae"),
        },
        RawRule {
            source: "(octop|vir|radi|nucle|fung|cact|stimul|alumn|calcul|hippopotam|macrofung|phoet|syllab|troph)us$",
            replacement: RawReplacement::Template("$1i"),
        },
        RawRule {
            source: "(buffal|tomat|tornad)o$",
            replacement: RawReplacement::Template("$1oes"),
        },
        RawRule {
            source: "(sis)$",
            replacement: RawReplacement::Template("ses"),
        },
        RawRule {
            source: "(matr|vert|ind|cort)(ix|ex)$",
            replacement: RawReplacement::Template("$1ices"),
        },
        RawRule {
            source: "sses$",
            replacement: RawReplacement::Template("sses"),
        },
        RawRule {
            source: "(x|ch|ss|sh|s|z)$",
            replacement: RawReplacement::Template("$1es"),
        },
        RawRule {
            source: "^(?!talis|.*hu)(.*)man$",
            replacement: RawReplacement::Template("$1men"),
        },
        RawRule {
            source: "(.*)",
            replacement: RawReplacement::Template("$1s"),
        },
    ];

    /// `singularForms.regularForms` in source order. First match wins.
    pub(crate) static SINGULAR_REGULAR: &[RawRule] = &[
        RawRule {
            source: "(.*)ves$",
            replacement: RawReplacement::Template("$1f"),
        },
        RawRule {
            source: "(.*)nses$",
            replacement: RawReplacement::Template("$1nse"),
        },
        RawRule {
            source: "([^v])ies$",
            replacement: RawReplacement::Template("$1y"),
        },
        RawRule {
            source: "ives$",
            replacement: RawReplacement::Template("ife"),
        },
        RawRule {
            source: "(antenn|formul|nebul|vertebr|vit)ae$",
            replacement: RawReplacement::Template("$1a"),
        },
        RawRule {
            source: "(octop|vir|radi|nucle|fung|cact|stimul|alumn|calcul|hippopotam|macrofung|phoet|syllab|troph)(i)$",
            replacement: RawReplacement::Template("$1us"),
        },
        RawRule {
            source: "(buffal|tomat|tornad)(oes)$",
            replacement: RawReplacement::Template("$1o"),
        },
        RawRule {
            source: "(analy|naly|synop|parenthe|diagno|the)ses$",
            replacement: RawReplacement::Template("$1sis"),
        },
        RawRule {
            source: "(vert|ind|cort)(ices)$",
            replacement: RawReplacement::Template("$1ex"),
        },
        RawRule {
            source: "(matr|append)(ices)$",
            replacement: RawReplacement::Template("$1ix"),
        },
        RawRule {
            source: "(x|ch|ss|sh|s|z)es$",
            replacement: RawReplacement::Template("$1"),
        },
        RawRule {
            source: "men$",
            replacement: RawReplacement::Template("man"),
        },
        RawRule {
            source: "ss$",
            replacement: RawReplacement::Template("ss"),
        },
        RawRule {
            source: "s$",
            replacement: RawReplacement::Template(""),
        },
    ];
}

/// French noun tables — the reference `noun_inflector`.
pub(crate) mod fr {
    use super::{RawReplacement, RawRule};

    /// `this.ambiguous`: words that inflect to themselves. Sorted here so the
    /// membership test is a binary search rather tha reference's linear
    /// `Array.indexOf`; order is not observable because only membership is.
    pub(crate) static AMBIGUOUS: &[&str] = &[
        "abat-voix",
        "abattis",
        "abcès",
        "abois",
        "abribus",
        "abus",
        "accès",
        "acquis",
        "adonis",
        "ados",
        "adénovirus",
        "afflux",
        "agrès",
        "aguets",
        "ailleurs",
        "ais",
        "albatros",
        "albinos",
        "alias",
        "allume-gaz",
        "aloès",
        "alpax",
        "amaryllis",
        "amas",
        "ampélopsis",
        "ananas",
        "anchois",
        "angélus",
        "anis",
        "anthrax",
        "anticorps",
        "antihéros",
        "antirides",
        "anus",
        "apex",
        "appas",
        "appentis",
        "appui-bras",
        "appuie-bras",
        "aptéryx",
        "arcanes",
        "archéoptéryx",
        "argus",
        "arrière-faix",
        "arrière-pays",
        "arrérages",
        "as",
        "ascaris",
        "asparagus",
        "assez",
        "atlas",
        "atours",
        "aurochs",
        "autobus",
        "autofocus",
        "avant-bras",
        "avant-corps",
        "avant-propos",
        "avers",
        "avis",
        "axis",
        "barbouillis",
        "bas",
        "beaujolais",
        "beaux-arts",
        "biais",
        "bibliobus",
        "biceps",
        "bicross",
        "bien-fonds",
        "biogaz",
        "bloc-notes",
        "blockhaus",
        "blocus",
        "blues",
        "bois",
        "bombyx",
        "bonus",
        "borax",
        "bordeaux",
        "bouseux",
        "bout-dehors",
        "bouts-rimés",
        "box",
        "branle-bas",
        "bras",
        "brebis",
        "bris",
        "brise-lames",
        "brise-mottes",
        "brûlis",
        "buis",
        "burnous",
        "bus",
        "business",
        "cabas",
        "cacatois",
        "cacatoès",
        "cache-nez",
        "cactus",
        "cadenas",
        "cafouillis",
        "caillebotis",
        "calvados",
        "cambouis",
        "camping-gaz",
        "campus",
        "canevas",
        "cannabis",
        "carex",
        "carquois",
        "cas",
        "casse-noisettes",
        "casse-noix",
        "casse-pieds",
        "cassis",
        "caucus",
        "cedex",
        "cens",
        "cervelas",
        "chablis",
        "chamois",
        "chaos",
        "chas",
        "chasselas",
        "chatouillis",
        "chauffe-assiettes",
        "chauve-souris",
        "chaux",
        "chez",
        "chintz",
        "choix",
        "chorus",
        "choucas",
        "châssis",
        "circoncis",
        "cirrus",
        "clafoutis",
        "clapotis",
        "cliquetis",
        "clos",
        "coccyx",
        "cochylis",
        "codex",
        "colis",
        "coloris",
        "commis",
        "compas",
        "compromis",
        "compte-chèques",
        "compte-gouttes",
        "compte-tours",
        "concours",
        "confins",
        "congrès",
        "consensus",
        "contrepoids",
        "contresens",
        "contretemps",
        "contumax",
        "coqueleux",
        "corn flakes",
        "corps",
        "corps-à-corps",
        "corpus",
        "cortex",
        "cosinus",
        "cosmos",
        "coulis",
        "coupe-ongles",
        "courroux",
        "cours",
        "court-jus",
        "couscous",
        "coutelas",
        "crocus",
        "croix",
        "croquis",
        "cross",
        "crucifix",
        "cubitus",
        "culex",
        "cumulus",
        "cure-dents",
        "cure-ongles",
        "cure-pipes",
        "cursus",
        "cyclo-cross",
        "cyprès",
        "céphalothorax",
        "cérambyx",
        "dais",
        "damas",
        "dedans",
        "dehors",
        "delirium tremens",
        "demi-gros",
        "demodex",
        "dessous",
        "dessus",
        "deux-mâts",
        "deux-pièces",
        "deux-points",
        "deux-roues",
        "deux-temps",
        "devis",
        "diplodocus",
        "discours",
        "dos",
        "duplex",
        "débarras",
        "débours",
        "débris",
        "décès",
        "dépens",
        "détritus",
        "dévers",
        "edelweiss",
        "embarras",
        "empois",
        "en-cas",
        "encens",
        "enclos",
        "endos",
        "engrais",
        "entre-deux",
        "entrelacs",
        "entremets",
        "envers",
        "ers",
        "ersatz",
        "espace-temps",
        "essuie-mains",
        "eucalyptus",
        "eux",
        "ex",
        "ex-libris",
        "excès",
        "express",
        "extrados",
        "faciès",
        "fait-divers",
        "faix",
        "fatras",
        "faucheux",
        "faux",
        "faux-sens",
        "favoris",
        "fax",
        "ferreux",
        "fez",
        "ficus",
        "fier-à-bras",
        "finnois",
        "florès",
        "flux",
        "focus",
        "fois",
        "forceps",
        "fouillis",
        "fox",
        "fracas",
        "frais",
        "franglais",
        "français",
        "free-jazz",
        "freux",
        "frimas",
        "friselis",
        "frisottis",
        "fritz",
        "froncis",
        "frottis",
        "fucus",
        "furax",
        "fœtus",
        "galetas",
        "galimatias",
        "garde-corps",
        "garde-à-vous",
        "gargouillis",
        "gars",
        "gaz",
        "gazouillis",
        "gibus",
        "gin-fizz",
        "glacis",
        "glas",
        "gneiss",
        "gobe-mouches",
        "gribouillis",
        "grès",
        "guet-apens",
        "gâchis",
        "gâte-bois",
        "génois",
        "habeas corpus",
        "hachis",
        "hapax",
        "haras",
        "hardes",
        "harengueux",
        "harnais",
        "haut-le-corps",
        "hautbois",
        "herbe-aux-chats",
        "herpès",
        "hertz",
        "hiatus",
        "hibiscus",
        "hors-concours",
        "hors-pistes",
        "horse-pox",
        "hourdis",
        "houx",
        "huis-clos",
        "humus",
        "humérus",
        "hélix",
        "héros",
        "ibis",
        "iléus",
        "index",
        "indique-fuites",
        "infarctus",
        "influx",
        "inlandsis",
        "inox",
        "insuccès",
        "intercours",
        "intrados",
        "intrus",
        "iris",
        "isatis",
        "jais",
        "jars",
        "jazz",
        "jeans",
        "jerez",
        "jeuconcours",
        "judas",
        "juke-box",
        "juliénas",
        "jus",
        "justaucorps",
        "kakatoès",
        "kermès",
        "kibboutz",
        "kilohertz",
        "kleenex",
        "kolkhoz",
        "kriss",
        "kronprinz",
        "lacis",
        "lagothrix",
        "lambris",
        "lapiaz",
        "lapis",
        "laps",
        "lapsus",
        "laquais",
        "larynx",
        "las",
        "lastex",
        "latex",
        "lattis",
        "lave-mains",
        "lavis",
        "laïus",
        "legs",
        "lez",
        "lias",
        "lilas",
        "lis",
        "liégeois",
        "logis",
        "loris",
        "lotus",
        "louis",
        "lupus",
        "lux",
        "lynx",
        "lys",
        "lèche-bottes",
        "lèche-vitrines",
        "lœss",
        "macareux",
        "madras",
        "malappris",
        "malus",
        "maquis",
        "marais",
        "maroilles",
        "marquis",
        "mas",
        "mass-médias",
        "matelas",
        "matois",
        "max",
        "maïs",
        "merguez",
        "mess",
        "mets",
        "mi-bas",
        "mi-voix",
        "micro-ondes",
        "mille-pattes",
        "millepertuis",
        "minibus",
        "minois",
        "minus",
        "mirabilis",
        "mirepoix",
        "mois",
        "monocorps",
        "monte-plats",
        "mors",
        "motocross",
        "mots-croisés",
        "motteux",
        "motus",
        "mouchetis",
        "mucus",
        "multiplex",
        "murex",
        "myosotis",
        "mâchicoulis",
        "mânes",
        "médius",
        "mégahertz",
        "mépris",
        "mérinos",
        "mésothorax",
        "narthex",
        "nez",
        "niais",
        "nimbo-stratus",
        "nimbus",
        "noix",
        "norois",
        "nounours",
        "nu-pieds",
        "nævus",
        "négus",
        "oasis",
        "obus",
        "olibrius",
        "omnibus",
        "onyx",
        "opopanax",
        "opus",
        "oropharynx",
        "os",
        "ours",
        "ouvre-bouteilles",
        "ouvre-boîtes",
        "paix",
        "palais",
        "palis",
        "palmarès",
        "palus",
        "panais",
        "panaris",
        "panax",
        "pancréas",
        "papyrus",
        "par-dehors",
        "paradis",
        "parcours",
        "pardessus",
        "pare-balles",
        "pare-chocs",
        "parvis",
        "pas",
        "passe-temps",
        "pataquès",
        "pathos",
        "patois",
        "pavois",
        "pays",
        "perdrix",
        "permis",
        "petit-bourgeois",
        "petit-gris",
        "petit-pois",
        "phallus",
        "pharynx",
        "phimosis",
        "phlox",
        "phoenix",
        "phénix",
        "pickles",
        "pilotis",
        "pince-nez",
        "pique-fleurs",
        "pis",
        "pithiviers",
        "pityriasis",
        "plateau-repas",
        "plein-temps",
        "plexiglas",
        "plexus",
        "plus",
        "plâtras",
        "pneumothorax",
        "poids",
        "pois",
        "poix",
        "pont-levis",
        "porte-avions",
        "porte-bagages",
        "porte-billets",
        "porte-bouteilles",
        "porte-clés",
        "porte-hélicoptères",
        "porte-jarretelles",
        "porte-revues",
        "portefaix",
        "pouls",
        "pousse-cailloux",
        "presse-fruits",
        "presse-papiers",
        "preux",
        "princeps",
        "printemps",
        "prix",
        "processus",
        "procès",
        "progrès",
        "propos",
        "prospectus",
        "prothorax",
        "protège-dents",
        "préavis",
        "psoriasis",
        "pubis",
        "pucheux",
        "puits",
        "pus",
        "putois",
        "pyrex",
        "pyroligneux",
        "quadruplex",
        "quartz",
        "quatre-feuilles",
        "quatre-heures",
        "quatre-mâts",
        "quatre-quarts",
        "quatre-temps",
        "quatre-épices",
        "queux",
        "quitus",
        "quiz",
        "rabais",
        "rachis",
        "radis",
        "radius",
        "ramassis",
        "ranz",
        "raz",
        "raïs",
        "recez",
        "reclus",
        "recours",
        "redoux",
        "reflex",
        "reflux",
        "refus",
        "relais",
        "relax",
        "remords",
        "remous",
        "remue-méninges",
        "rendez-vous",
        "repas",
        "repos",
        "repris",
        "reps",
        "revers",
        "rez",
        "rhinocéros",
        "rhinopharynx",
        "rictus",
        "rince-doigts",
        "ris",
        "riz",
        "rollmops",
        "rose-croix",
        "rosé-des-prés",
        "roulis",
        "rouvieux",
        "roux",
        "rubis",
        "rumex",
        "ruolz",
        "rébus",
        "rémiz",
        "répons",
        "rétrovirus",
        "saindoux",
        "salmigondis",
        "salsifis",
        "sans-logis",
        "sardonyx",
        "sas",
        "sassafras",
        "sauternes",
        "schnaps",
        "schuss",
        "scolex",
        "secours",
        "seltz",
        "semis",
        "sens",
        "serre-fils",
        "serre-livres",
        "serre-nez",
        "silex",
        "simplex",
        "sinus",
        "sioux",
        "sirex",
        "skunks",
        "smilax",
        "solex",
        "songe-creux",
        "souris",
        "sournois",
        "sous-bois",
        "spalax",
        "sphex",
        "sphinx",
        "storax",
        "stradivarius",
        "stras",
        "strass",
        "strato-cumulus",
        "stratus",
        "stress",
        "strix",
        "styrax",
        "succès",
        "surdos",
        "surfaix",
        "surplus",
        "surpoids",
        "sursis",
        "surtaux",
        "suspens",
        "synopsis",
        "syphilis",
        "syrinx",
        "sèche-cheveux",
        "sévices",
        "taffetas",
        "taillis",
        "talus",
        "tamaris",
        "tamarix",
        "tamis",
        "tapis",
        "tas",
        "taudis",
        "taux",
        "temps",
        "tennis",
        "terminus",
        "terre-neuvas",
        "thalamus",
        "thermos",
        "thesaurus",
        "thorax",
        "thymus",
        "thésaurus",
        "tire-fesses",
        "tonus",
        "torchis",
        "tord-boyaux",
        "torticolis",
        "tournedos",
        "tournevis",
        "tournis",
        "toux",
        "tracas",
        "travers",
        "traîne-savates",
        "treillis",
        "trias",
        "triceps",
        "trichomonas",
        "trionyx",
        "tripoux",
        "trois-mâts",
        "trois-quarts",
        "trois-étoiles",
        "trolleybus",
        "tréfonds",
        "trépas",
        "tubifex",
        "tumulus",
        "typhus",
        "télex",
        "tétanos",
        "tétras",
        "univers",
        "us",
        "utérus",
        "vasistas",
        "velours",
        "verglas",
        "verjus",
        "vernis",
        "vers",
        "vert-de-gris",
        "vertex",
        "vide-ordures",
        "vide-poches",
        "vidéotex",
        "vielleux",
        "vieux",
        "villageois",
        "violoneux",
        "virus",
        "vis-à-vis",
        "voix",
        "volubilis",
        "volvox",
        "vortex",
        "vulgum pecus",
        "vélocross",
        "waters",
        "williams",
        "xérès",
        "à-peu-près",
        "à-propos",
        "ébats",
        "éboulis",
        "échalas",
        "élaeis",
        "éleis",
        "éléphantiasis",
        "épluche-légumes",
        "époux",
        "équivaux",
    ];

    /// `pluralForms.irregularForms`: singular -> plural, after the
    /// last-write-wins collapse `addForm` performs. Sorted by key.
    pub(crate) static PLURAL_IRREGULAR: &[(&str, &str)] = &[
        ("ail", "aulx"),
        ("bonhomme", "bonshommes"),
        ("bétail", "bestiaux"),
        ("ciel", "cieux"),
        ("mafioso", "mafiosi"),
        ("monsieur", "messieurs"),
        ("putto", "putti"),
        ("targui", "touareg"),
        ("œil", "yeux"),
    ];

    /// `singularForms.irregularForms`: plural -> singular, likewise collapsed.
    pub(crate) static SINGULAR_IRREGULAR: &[(&str, &str)] = &[
        ("aulx", "ail"),
        ("bestiaux", "bétail"),
        ("bonshommes", "bonhomme"),
        ("cieux", "ciel"),
        ("mafiosi", "mafioso"),
        ("messieurs", "monsieur"),
        ("putti", "putto"),
        ("touareg", "targui"),
        ("yeux", "œil"),
    ];

    /// `pluralForms.regularForms` in source order. First match wins.
    pub(crate) static PLURAL_REGULAR: &[RawRule] = &[
        RawRule {
            source: "^(av|b|c|carnav|cérémoni|chac|corr|emment|emmenth|festiv|fut|gavi|gra|narv|p|récit|rég|rit|rorqu|st)al$",
            replacement: RawReplacement::Template("$1als"),
        },
        RawRule {
            source: "^(aspir|b|cor|ém|ferm|gemm|soupir|trav|vant|vent|vitr)ail$",
            replacement: RawReplacement::Template("$1aux"),
        },
        RawRule {
            source: "^(bij|caill|ch|gen|hib|jouj|p|rip|chouch)ou$",
            replacement: RawReplacement::Template("$1oux"),
        },
        RawRule {
            source: "^(gr|berimb|don|karb|land|pil|rest|sarr|un)au$",
            replacement: RawReplacement::Template("$1aus"),
        },
        RawRule {
            source: "^(bl|ém|enf|pn)eu$",
            replacement: RawReplacement::Template("$1eus"),
        },
        RawRule {
            source: "(au|eau|eu|œu)$",
            replacement: RawReplacement::Template("$1x"),
        },
        RawRule {
            source: "al$",
            replacement: RawReplacement::Template("aux"),
        },
        RawRule {
            source: "(s|x)$",
            replacement: RawReplacement::Template("$1"),
        },
        RawRule {
            source: "(.*)$",
            replacement: RawReplacement::Template("$1s"),
        },
    ];

    /// `singularForms.regularForms` in source order. First match wins.
    pub(crate) static SINGULAR_REGULAR: &[RawRule] = &[
        RawRule {
            source: "^(aspir|b|cor|ém|ferm|gemm|soupir|trav|vant|vent|vitr)aux$",
            replacement: RawReplacement::Template("$1ail"),
        },
        RawRule {
            source: "^(aloy|b|bouc|boy|burg|conoy|coy|cr|esquim|ét|fabli|flé|flûti|glu|gr|gru|hoy|joy|kérab|matéri|nobli|noy|pré|sen|sén|t|touch|tuss|tuy|v|ypré)aux$",
            replacement: RawReplacement::Template("$1au"),
        },
        RawRule {
            source: "^(bij|caill|ch|gen|hib|jouj|p|rip|chouch)oux$",
            replacement: RawReplacement::Template("$1ou"),
        },
        RawRule {
            source: "^(bis)?aïeux$",
            replacement: RawReplacement::Template("$1aïeul"),
        },
        RawRule {
            source: "^apparaux$",
            replacement: RawReplacement::Template("appareil"),
        },
        RawRule {
            source: "^ciels$",
            replacement: RawReplacement::Template("ciel"),
        },
        RawRule {
            source: "^œils$",
            replacement: RawReplacement::Template("œil"),
        },
        RawRule {
            source: "(eau|eu|œu)x$",
            replacement: RawReplacement::Template("$1"),
        },
        RawRule {
            source: "aux$",
            replacement: RawReplacement::Template("al"),
        },
        RawRule {
            source: "(.*)s$",
            replacement: RawReplacement::Template("$1"),
        },
    ];
}

/// Japanese noun tables — the reference `noun_inflector`.
pub(crate) mod ja {
    use super::{RawReplacement, RawRule};

    /// `this.ambiguous`: words that inflect to themselves. Sorted here so the
    /// membership test is a binary search rather tha reference's linear
    /// `Array.indexOf`; order is not observable because only membership is.
    pub(crate) static AMBIGUOUS: &[&str] = &[
        "ともだち",
        "友だち",
        "友達",
        "女友達",
        "学校友達",
        "幼友達",
        "男友達",
        "茶飲み友達",
        "遊び友達",
        "酒飲み友達",
        "飲み友達",
    ];

    /// `pluralForms.irregularForms`: singular -> plural, after the
    /// last-write-wins collapse `addForm` performs. Sorted by key.
    pub(crate) static PLURAL_IRREGULAR: &[(&str, &str)] = &[
        ("人", "人人"),
        ("国", "国国"),
        ("山", "山山"),
        ("島", "島島"),
        ("年", "年年"),
        ("我", "我我"),
        ("所", "所所"),
        ("日", "日日"),
        ("星", "星星"),
        ("月", "月月"),
        ("神", "神神"),
        ("隅", "隅隅"),
    ];

    /// `singularForms.irregularForms`: plural -> singular, likewise collapsed.
    pub(crate) static SINGULAR_IRREGULAR: &[(&str, &str)] = &[
        ("人人", "人"),
        ("国国", "国"),
        ("山山", "山"),
        ("島島", "島"),
        ("年年", "年"),
        ("我我", "我"),
        ("所所", "所"),
        ("日日", "日"),
        ("星星", "星"),
        ("月月", "月"),
        ("神神", "神"),
        ("隅隅", "隅"),
    ];

    /// `pluralForms.regularForms` in source order. First match wins.
    pub(crate) static PLURAL_REGULAR: &[RawRule] = &[RawRule {
        source: "^(.+)$",
        replacement: RawReplacement::Template("$1たち"),
    }];

    /// `singularForms.regularForms` in source order. First match wins.
    pub(crate) static SINGULAR_REGULAR: &[RawRule] = &[
        RawRule {
            source: "^(.+)たち$",
            replacement: RawReplacement::KeepIfListed {
                exceptions: &[
                    "い",
                    "おい",
                    "つい",
                    "か",
                    "かおか",
                    "なりか",
                    "いで",
                    "は",
                    "から",
                    "なり",
                ],
                suffix: "たち",
            },
        },
        RawRule {
            source: "^(.+)達$",
            replacement: RawReplacement::KeepIfListed {
                exceptions: &[
                    "伊",
                    "伊",
                    "栄",
                    "上意下",
                    "熟",
                    "上",
                    "下意上",
                    "先",
                    "送",
                    "速",
                    "即日速",
                    "書留速",
                    "調",
                    "通",
                    "伝",
                    "到",
                    "配",
                    "牛乳配",
                    "新聞配",
                    "無料配",
                    "四通八",
                    "発",
                    "未発",
                    "御用",
                    "宮内庁御用",
                    "練",
                    "闊",
                ],
                suffix: "達",
            },
        },
        RawRule {
            source: "^(.+)等$",
            replacement: RawReplacement::KeepIfListed {
                exceptions: &[
                    "一",
                    "下",
                    "何",
                    "均",
                    "勲",
                    "高",
                    "三",
                    "初",
                    "親",
                    "二親",
                    "数",
                    "対",
                    "中",
                    "同",
                    "特",
                    "二",
                    "品",
                    "不",
                    "平",
                    "悪平",
                    "男女平",
                    "不平",
                    "優",
                    "劣",
                ],
                suffix: "等",
            },
        },
        RawRule {
            source: "^(人間|わたくし|私|てまえ|手前|野郎|やろう|勇者|がき|ガキ|餓鬼|あくとう|悪党|猫|家来)(共|ども)$",
            replacement: RawReplacement::Template("$1"),
        },
        RawRule {
            source: "^(神様|先生|あなた|大名|女中|奥様)(方|がた)$",
            replacement: RawReplacement::Template("$1"),
        },
    ];
}

/// Present-tense verb tables — the reference `present_verb_inflector`.
pub(crate) mod verb {
    use super::{RawReplacement, RawRule};

    /// `this.ambiguous`: words that inflect to themselves. Sorted here so the
    /// membership test is a binary search rather tha reference's linear
    /// `Array.indexOf`; order is not observable because only membership is.
    pub(crate) static AMBIGUOUS: &[&str] = &["will"];

    /// `pluralForms.irregularForms`: singular -> plural, after the
    /// last-write-wins collapse `addForm` performs. Sorted by key.
    pub(crate) static PLURAL_IRREGULAR: &[(&str, &str)] = &[
        ("am", "are"),
        ("has", "have"),
        ("is", "are"),
        ("was", "were"),
    ];

    /// `singularForms.irregularForms`: plural -> singular, likewise collapsed.
    pub(crate) static SINGULAR_IRREGULAR: &[(&str, &str)] =
        &[("are", "is"), ("have", "has"), ("were", "was")];

    /// `pluralForms.regularForms` in source order. First match wins.
    pub(crate) static PLURAL_REGULAR: &[RawRule] = &[
        RawRule {
            source: "sses$",
            replacement: RawReplacement::Template("ss"),
        },
        RawRule {
            source: "xes$",
            replacement: RawReplacement::Template("x"),
        },
        RawRule {
            source: "([cs])hes$",
            replacement: RawReplacement::Template("$1h"),
        },
        RawRule {
            source: "zzes$",
            replacement: RawReplacement::Template("zz"),
        },
        RawRule {
            source: "([^h|z|o|i])es$",
            replacement: RawReplacement::Template("$1e"),
        },
        RawRule {
            source: "ies$",
            replacement: RawReplacement::Template("y"),
        },
        RawRule {
            source: "e?s$",
            replacement: RawReplacement::Template(""),
        },
    ];

    /// `singularForms.regularForms` in source order. First match wins.
    pub(crate) static SINGULAR_REGULAR: &[RawRule] = &[
        RawRule {
            source: "ed$",
            replacement: RawReplacement::Template("ed"),
        },
        RawRule {
            source: "ss$",
            replacement: RawReplacement::Template("sses"),
        },
        RawRule {
            source: "x$",
            replacement: RawReplacement::Template("xes"),
        },
        RawRule {
            source: "(h|z|o)$",
            replacement: RawReplacement::Template("$1es"),
        },
        RawRule {
            source: "$zz",
            replacement: RawReplacement::Template("zzes"),
        },
        RawRule {
            source: "([^a|e|i|o|u])y$",
            replacement: RawReplacement::Template("$1ies"),
        },
        RawRule {
            source: "$",
            replacement: RawReplacement::Template("s"),
        },
    ];
}
