#!/usr/bin/env bash
# Every directory of shipped data must record where its contents came from.
#
# AGENTS.md's `# Licensing` section is the rule; this is what makes it fail.
# The previous version of that section was advice, and advice let 4.5 MB of
# LGPL-3.0 and unlicensable dictionaries ship in an MIT crate for two published
# versions. A rule nothing enforces gets skipped by whoever is in a hurry,
# which is everyone.
#
# The check is deliberately weak but not vacuous: a `NOTICE.md` or `README.md`
# must exist AND name both a source and terms. Checking only that a file exists
# would pass on a README saying "test fixtures", which is the shape of every
# test in this repo that turned out to assert nothing.
#
# What it cannot catch: a notice naming the wrong licence, or data embedded in
# a `.rs` file — see `crates/verbora-stemmers/src/data/indonesian_dict.rs`,
# 29,932 words whose source is unknown and which this script cannot see.
set -euo pipefail

cd "$(dirname "$0")/.."
missing=() thin=()

while IFS= read -r dir; do
    doc=""
    for candidate in "$dir/NOTICE.md" "$dir/README.md"; do
        [ -f "$candidate" ] && { doc="$candidate"; break; }
    done
    if [ -z "$doc" ]; then
        doc=$(find "$dir" -maxdepth 2 \( -name NOTICE.md -o -name README.md \) -print -quit)
    fi
    if [ -z "$doc" ]; then
        missing+=("$dir")
        continue
    fi
    # A source (a URL, or an explicit statement that Verbora produced it) and
    # terms (a licence word). Both, or the notice is decoration.
    has_source=$(grep -ciE 'https?://|generated by|derived from|produced by' "$doc" || true)
    has_terms=$(grep -ciE 'licen[sc]e|copyright|public domain|terms of use' "$doc" || true)
    if [ "$has_source" -eq 0 ] || [ "$has_terms" -eq 0 ]; then
        thin+=("$doc — source:$has_source terms:$has_terms")
    fi
done < <(find crates -type d -name data -not -path '*/target/*' | sort)

status=0
if [ ${#missing[@]} -gt 0 ]; then
    status=1
    echo "FAIL — shipped data with no provenance record:"
    for d in "${missing[@]}"; do
        printf '  %-46s %s\n' "$d" "$(du -sh "$d" | cut -f1)"
    done
fi
if [ ${#thin[@]} -gt 0 ]; then
    status=1
    echo "FAIL — provenance record names no source, or no terms:"
    printf '  %s\n' "${thin[@]}"
fi

if [ $status -ne 0 ]; then
    cat <<'MSG'

Each needs a NOTICE.md (or README.md) stating where the data came from, under
what terms, and at what version or hash. Model it on
crates/verbora-phonetics/data/beider-morse/NOTICE.md.

If you cannot establish the terms, the data does not ship: AGENTS.md's
`# Licensing` treats an unlocatable licence as a refusal, not as permission.
MSG
    exit 1
fi

echo "OK — every shipped data directory names a source and its terms."
