//! Twenty-five text tokenizers for Rust.
//!
//! All twenty-five tokenizers exported by the reference `tokenizers` module, reproduced
//! down to the bugs. Where the reference does something surprising — German
//! treats `Ä` as a separator, Indonesian deletes every capital letter, the case
//! tokenizer appends the literal string `"undefined"` — this crate does the same
//! thing, and says why in the doc comment.
//!
//! # Iterator first
//!
//! Every tokenizer is built around a lazy iterator; the convenience methods are
//! defined on top of it, so there is one implementation of the behaviour and no
//! second copy to drift:
//!
//! ```
//! use verbora_tokenizers::{AggressiveTokenizer, Tokenize};
//!
//! let t = AggressiveTokenizer::new();
//!
//! // Lazy, zero-copy: each token borrows the input.
//! let first = t.tokens("the quick brown fox").next();
//! assert_eq!(first, Some("the"));
//!
//! // Collected.
//! assert_eq!(t.tokenize("the quick"), ["the", "quick"]);
//!
//! // Into a buffer the caller reuses across documents.
//! let mut buf = Vec::new();
//! for doc in ["one two", "three four"] {
//!     buf.clear();
//!     t.tokenize_into(doc, &mut buf);
//! }
//! ```
//!
//! # What each tokenizer's tokens are made of
//!
//! The token type is chosen per tokenizer to describe what that tokenizer can
//! honestly produce, rather than being flattened to `String` everywhere:
//!
//! | Token type | Tokenizers | Why |
//! |---|---|---|
//! | `&'a str` | the thirteen character-class tokenizers, [`WordTokenizer`] | every token is a slice of the input; nothing is allocated per token |
//! | `Cow<'a, str>` | [`AggressiveTokenizerNo`], [`AggressiveTokenizerSv`], [`AggressiveTokenizerHi`] | these rewrite the text first (diacritics, deleted punctuation), so they borrow when the rewrite was a no-op and copy when it was not |
//! | [`Utf16Token`] | [`WordPunctTokenizer`], [`TreebankWordTokenizer`], [`TokenizerJa`], [`CaseTokenizer`], [`OrthographyTokenizer`] | these cut at UTF-16 code-unit boundaries, so an astral character becomes two tokens holding **unpaired surrogates** — values no `String` can hold. Treebank and WordPunct still borrow every well-formed token |
//! | `Option<&'a str>` | [`RegexpTokenizer`] | a capture group that did not participate is the reference's `undefined` |
//! | `String` | [`SentenceTokenizer`] | placeholder substitution rewrites the text |
//!
//! # Parity hazards this crate handles
//!
//! * **UTF-16 indexing.** `"a😀b"` is four code units to the reference. Four
//!   tokenizers therefore split emoji in half; see [`Utf16Token`].
//! * **ASCII-scoped `\w`, `\W`, `\b`, `\d`.** Rust's `regex` makes them
//!   Unicode-aware by default, which changes Italian tokenization and every
//!   Treebank contraction boundary.
//! * **`/i` is not case folding.** The reference language never folds a non-ASCII character
//!   onto an ASCII one, so `ſ` does not match `s` and `K` does not match `k`;
//!   Rust's `(?i)` folds both. Character classes here are generated by running
//!   The reference regexes over the whole BMP rather than transcribed.
//! * **`String#replace` with a string pattern replaces only the first match.**
//!   Rust's [`str::replace`] replaces all of them, which changes Norwegian and
//!   Swedish output on any repeated accent.
//! * **`\s` is not `char::is_whitespace`.** U+FEFF is whitespace to the reference
//!   and not to Rust; U+0085 is the reverse. See [`whitespace`].
//! * **`Tokenizer#trim` removes empty tokens from the two ends only.** Interior
//!   empties survive, which is visible in [`SentenceTokenizer`].
//!
//! # Relationship to `verbora_core`
//!
//! Tokenizers whose tokens are text also implement [`verbora_core::Tokenizer`]
//! (and, where they borrow, [`verbora_core::BorrowingTokenizer`]) so that
//! downstream crates written against the shared vocabulary can use them. Both
//! that trait and [`Tokenize`] have a `tokenize` method, so importing both into
//! one scope makes an unqualified call ambiguous; prefer importing just the one
//! you need.
//!
//! The four regex-driven tokenizers implement neither, because `String#match`
//! can return `null` and the traits have no way to say so. They expose the same
//! `tokens` / `tokenize` / `tokenize_into` shape wrapped in [`Option`].

pub mod aggressive;
pub mod case;
pub mod classes;
pub mod ja;
pub mod regexp;
pub mod scan;
pub mod sentence;
pub mod treebank;
pub mod utf16;
pub mod whitespace;

pub use aggressive::{
    AggressiveTokenizer, AggressiveTokenizerDe, AggressiveTokenizerEs, AggressiveTokenizerFa,
    AggressiveTokenizerFr, AggressiveTokenizerHi, AggressiveTokenizerId, AggressiveTokenizerIt,
    AggressiveTokenizerNl, AggressiveTokenizerNo, AggressiveTokenizerPl, AggressiveTokenizerPt,
    AggressiveTokenizerRu, AggressiveTokenizerSv, AggressiveTokenizerUk, AggressiveTokenizerVi,
};
pub use case::CaseTokenizer;
pub use ja::TokenizerJa;
pub use regexp::{
    OrthographyTokenizer, Pattern, RegexpTokenizer, WordPunctTokenizer, WordTokenizer,
};
pub use sentence::{SentenceTokenizer, SentenceTokenizerNew};
pub use treebank::TreebankWordTokenizer;
pub use utf16::Utf16Token;

/// A tokenizer, expressed as a lazy iterator.
///
/// [`Self::tokens`] is the only method an implementation must write; the other
/// two are defined in terms of it, so there is a single source of behaviour.
///
/// The associated type is generic over the input's lifetime so that a tokenizer
/// which only *slices* its input can say so — `type Token<'a> = &'a str` — while
/// one that must rewrite it can return owned or [`std::borrow::Cow`] tokens
/// without every caller paying for the possibility.
pub trait Tokenize {
    /// What one token is: `&'a str`, `Cow<'a, str>`, [`Utf16Token`] or `String`,
    /// depending on what the tokenizer can produce. See the crate documentation
    /// for the table.
    type Token<'a>;

    /// Lazily yields the tokens of `text`.
    fn tokens<'a>(&self, text: &'a str) -> impl Iterator<Item = Self::Token<'a>>;

    /// Collects every token.
    fn tokenize<'a>(&self, text: &'a str) -> Vec<Self::Token<'a>> {
        self.tokens(text).collect()
    }

    /// Appends every token to `out`.
    ///
    /// `out` is **not** cleared, so a caller can accumulate across inputs or —
    /// the intended use — reuse one buffer's capacity across a corpus.
    fn tokenize_into<'a>(&self, text: &'a str, out: &mut Vec<Self::Token<'a>>) {
        out.extend(self.tokens(text));
    }

    /// Tokenizes many independent documents in parallel, using `rayon`.
    ///
    /// Requires the `parallel` feature.
    ///
    /// # Why this exists
    ///
    /// Every tokenizer in this crate that implements `Tokenize` is a plain
    /// value with no interior mutability — most are zero-sized — so running
    /// one stateless instance over many independent documents has no
    /// coordination cost between documents. This method is exactly
    /// `texts.par_iter().map(|t| self.tokenize(t)).collect()`: a thin `rayon`
    /// fan-out over [`Self::tokenize`], not a second implementation of
    /// tokenization. [`Self::tokens`] and [`Self::tokenize_into`] are
    /// untouched by this method and remain the primitives everything else is
    /// built on; if you need the buffer-reusing shape in parallel, combine
    /// `par_iter` with `map_init` at your own call site (see
    /// `site/performance/parallelism.md`'s "With a per-thread buffer"
    /// section).
    ///
    /// # When to reach for it vs. [`Self::tokenize`] / a sequential loop
    ///
    /// This crate's own benchmarks put a single `tokenize` call over an
    /// ~8192-word document at roughly 118–120 microseconds, and — per this
    /// crate's `api-shape` benchmark group — `tokenize` and `tokenize_into`
    /// cost about the same per call, so there is no cheaper sequential
    /// primitive to fall back to. A `rayon` task still costs on the order of
    /// a microsecond to schedule, so per-document parallelism only pays for
    /// itself once the batch is large enough, or the documents are large
    /// enough, that scheduling overhead is a small fraction of the total.
    /// Measure your own workload; for a handful of short strings prefer a
    /// plain `texts.iter().map(|t| self.tokenize(t))` loop, which is what
    /// this method degrades to per-item, minus the parallel scheduling.
    ///
    /// # Allocation behaviour
    ///
    /// One outer `Vec` sized to `texts.len()`, plus whatever [`Self::tokenize`]
    /// itself allocates per document — one `Vec<Self::Token<'_>>` growing to
    /// that document's token count. No buffer is shared across documents
    /// (parallel workers cannot share a `&mut Vec`) and no thread pool is
    /// constructed per call: this uses whichever global `rayon` pool is
    /// already installed, or `rayon`'s default one, so pool configuration
    /// remains the caller's responsibility, not this crate's.
    ///
    /// # Order
    ///
    /// Output order matches input order: `results[i]` is `self.tokenize(texts[i])`,
    /// via `rayon`'s order-preserving `map` + `collect`.
    #[cfg(feature = "parallel")]
    fn par_tokenize_batch<'a>(&self, texts: &[&'a str]) -> Vec<Vec<Self::Token<'a>>>
    where
        Self: Sync,
        Self::Token<'a>: Send,
    {
        use rayon::prelude::*;
        texts.par_iter().map(|text| self.tokenize(text)).collect()
    }
}

/// Removes empty tokens from both ends of a list — the reference's
/// `Tokenizer#trim`.
///
/// Re-exported from `verbora_core` because it is part of this cluster's
/// contract: it removes **only** the leading and trailing empties, leaving
/// interior ones alone, and that asymmetry is observable in
/// [`SentenceTokenizer`] (`"   "` tokenizes to `[""]`, not `[]`).
pub use verbora_core::trim_edge_empties;

#[cfg(test)]
mod tests {
    use super::*;

    /// The pathological-input battery every tokenizer in this crate is
    /// exercised against — empty, whitespace-only, every reference-whitespace
    /// oddity, and a script/astral/case-folding sweep. Shared at module scope
    /// so more than one test can reuse it rather than inventing new edge
    /// cases.
    const INPUTS: &[&str] = &[
        "",
        " ",
        "\t\n\r",
        "\u{feff}",
        "\u{85}",
        "a",
        "Z",
        "0",
        "!",
        "...",
        "--",
        "don't",
        "ALLCAPS",
        "café",
        "Ångström",
        "straße",
        "Москва",
        "Ελλάδα",
        "العربية",
        "日本語",
        "한국어",
        "ภาษาไทย",
        "हिन्दी",
        "e\u{301}",
        "😀",
        "a😀b",
        "𝕳𝖊𝖑𝖑𝖔",
        "İstanbul",
        "\u{212a}\u{17f}",
    ];

    /// Every tokenizer must survive the whole awkward-input battery without
    /// panicking, whatever it decides the answer is.
    #[test]
    fn nothing_panics_on_pathological_input() {
        for s in INPUTS {
            let _ = AggressiveTokenizer::new().tokenize(s);
            let _ = AggressiveTokenizerNl::new().tokenize(s);
            let _ = AggressiveTokenizerFa::new().tokenize(s);
            let _ = AggressiveTokenizerFr::new().tokenize(s);
            let _ = AggressiveTokenizerDe::new().tokenize(s);
            let _ = AggressiveTokenizerRu::new().tokenize(s);
            let _ = AggressiveTokenizerEs::new().tokenize(s);
            let _ = AggressiveTokenizerIt::new().tokenize(s);
            let _ = AggressiveTokenizerPl::new().tokenize(s);
            let _ = AggressiveTokenizerPt::new().tokenize(s);
            let _ = AggressiveTokenizerNo::new().tokenize(s);
            let _ = AggressiveTokenizerSv::new().tokenize(s);
            let _ = AggressiveTokenizerVi::new().tokenize(s);
            let _ = AggressiveTokenizerId::new().tokenize(s);
            let _ = AggressiveTokenizerHi::new().tokenize(s);
            let _ = AggressiveTokenizerUk::new().tokenize(s);
            let _ = CaseTokenizer::new().tokenize(s);
            let _ = CaseTokenizer::preserving_apostrophes().tokenize(s);
            let _ = WordTokenizer::new().tokenize(s);
            let _ = WordTokenizer::matching().tokenize(s);
            let _ = OrthographyTokenizer::new("fi").tokenize(s);
            let _ = OrthographyTokenizer::new("zz").tokenize(s);
            let _ = WordPunctTokenizer::new().tokenize(s);
            let _ = WordPunctTokenizer::matching().tokenize(s);
            let _ = TreebankWordTokenizer::new().tokenize(s);
            let _ = TokenizerJa::new().tokenize(s);
            let _ = SentenceTokenizer::new().tokenize(s);
            let _ = SentenceTokenizer::with_abbreviations(["e.g.", "i.e."]).tokenize(s);
            let _ = RegexpTokenizer::without_pattern().tokenize(s);
        }
    }

    /// `par_tokenize_batch` must produce exactly what a sequential loop over
    /// `tokenize` produces.
    ///
    /// Reuses `INPUTS` — the same pathological-input battery every tokenizer
    /// in this crate is already exercised against above, covering every
    /// script and the reference-whitespace/astral/case-folding oddities — rather
    /// than inventing new edge cases, and additionally covers the
    /// empty-batch and single-item edges that battery does not exercise on
    /// its own. Tokenizers are chosen to cover every `Token` shape this crate
    /// produces: `&str`, `Cow<str>`, [`utf16::Utf16Token`] and `String`.
    #[cfg(feature = "parallel")]
    #[test]
    fn par_tokenize_batch_matches_sequential_loop() {
        fn check<T>(t: &T, texts: &[&str])
        where
            T: Tokenize + Sync,
            for<'a> T::Token<'a>: Send + PartialEq + std::fmt::Debug,
        {
            let sequential: Vec<Vec<T::Token<'_>>> = texts.iter().map(|s| t.tokenize(s)).collect();
            let parallel = t.par_tokenize_batch(texts);
            assert_eq!(sequential, parallel);
        }

        // Empty batch: no documents at all.
        check(&AggressiveTokenizer::new(), &[]);
        // A single document.
        check(&AggressiveTokenizer::new(), &["hello world"]);
        // Many documents, covering every `Token` shape.
        check(&AggressiveTokenizer::new(), INPUTS); // &str
        check(&AggressiveTokenizerHi::new(), INPUTS); // Cow<str>
        check(&CaseTokenizer::new(), INPUTS); // Utf16Token
        check(&TreebankWordTokenizer::new(), INPUTS); // Utf16Token
        check(&TokenizerJa::new(), INPUTS); // Utf16Token
        check(&SentenceTokenizer::new(), INPUTS); // String
    }
}
