//! Turns the one bundled data file into a `&'static [&'static str]`.
//!
//! # Why a build script for ten strings
//!
//! Because the rules are *data with a citation*, and the citation is easier to
//! keep honest when the rules live in a file that can be diffed against Table 1
//! of the paper than when they are inlined in a `.rs` among code. `data/NOTICE.md`
//! records the provenance; this script is what stops the file from being
//! decorative.
//!
//! Ten short strings do not need a packed binary format, and no longer get one.
//! Earlier versions of this crate bundled multi-megabyte JSON dictionaries and
//! packed them at build time into a byte-sorted arena so that start-up parsed
//! nothing. Those dictionaries were removed for licensing reasons — see
//! `data/NOTICE.md` — and with them every reason for that machinery. What is left
//! is one `serde_json` parse of a small file at build time, emitting a `static`
//! array; nothing is parsed at run time either, so the property the packer
//! existed for is kept for free.

use std::fmt::Write as _;
use std::path::PathBuf;

use serde::Deserialize;

/// `{ "rules": [...] }`, the shape of the bundled rule file.
#[derive(Deserialize)]
struct RuleFile {
    rules: Vec<String>,
}

fn main() {
    let root = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("cargo sets this"));
    let out = PathBuf::from(std::env::var("OUT_DIR").expect("cargo sets this"));

    const SRC: &str = "English/tr_from_brill_paper.json";
    println!("cargo:rerun-if-changed=data/{SRC}");
    println!("cargo:rerun-if-changed=build.rs");

    let path = root.join("data").join(SRC);
    let text = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()));
    let file: RuleFile =
        serde_json::from_str(&text).unwrap_or_else(|e| panic!("cannot parse {SRC}: {e}"));

    let mut generated = String::from("// @generated by build.rs — do not edit.\n");
    writeln!(
        generated,
        "/// The ten rules published in Brill (1992), Table 1 (`data/{SRC}`)."
    )
    .unwrap();
    writeln!(
        generated,
        "pub(crate) static BRILL_1992_RULES: &[&str] = &["
    )
    .unwrap();
    for r in &file.rules {
        writeln!(generated, "    {r:?},").unwrap();
    }
    writeln!(generated, "];").unwrap();

    std::fs::write(out.join("generated.rs"), generated).expect("write generated.rs");
}
